#
# tuned configuration
#

[main]
summary=General non-specialized tuned profile for Alienware

[modules]
cpufreq_conservative=+r

[cpu]
priority=10
# https://docs.kernel.org/admin-guide/pm/cpufreq.html#generic-scaling-governors
## cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
governor=powersave
# https://www.kernel.org/doc/html/latest/admin-guide/pm/intel_epb.html
## cat /sys/devices/system/cpu/cpu0/power/energy_perf_bias
energy_perf_bias=normal
# https://wiki.archlinux.org/title/CPU_frequency_scaling#Setting_the_EPP
## cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences
energy_performance_preference=balance_power
boost=1

[acpi]
# https://docs.kernel.org/userspace-api/sysfs-platform_profile.html
## cat /sys/firmware/acpi/platform_profile_choices
platform_profile=balanced

[audio]
timeout=10

[video]
radeon_powersave=dpm-balanced, auto
panel_power_savings=0

[disk]
# Comma separated list of devices, all devices if commented out.
# devices=sda

[scsi_host]
alpm=med_power_with_dipm
