; https://looking-glass.io/ ---> Search for the command line options available
[audio]
bufferLatency=4

[input]
escapeKey=KEY_HOME

[spice]
enable=yes
audio=yes
clipboard=yes
host=/tmp/vm_spice.sock
port=0

[win]
forceAspect=yes
keepAspect=yes
jitRender=yes
noScreensaver=no
position=center
showFPS=yes
size=1920x1080
uiFont=/usr/share/fonts/TTF/DejaVuSansMNerdFont-Regular.ttf
uiSize=16
