#!/hint/bash
# shellcheck disable=2034

#
# /etc/makepkg.conf.d/tmp-build-dir.conf
#

## https://wiki.archlinux.org/title/Makepkg#Building_from_files_in_memory
# Also see makepkg.conf(5)
BUILDDIR=/tmp/makepkg
