## https://man.archlinux.org/man/core/systemd/sleep.conf.d.5.en#OPTIONS
## https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#System_does_not_power_off_when_hibernating

[Sleep]
HibernateMode=platform
