## https://this.ven.uber.space/docs/computer/pro-audio/#sound-server

context.properties = {
    ## https://wiki.archlinux.org/title/PipeWire#Changing_the_allowed_sample_rate(s)
    default.clock.allowed-rates = [ 44100 48000 ] # Values set according to: cat /proc/asound/card0/stream0 (my audio interface)

    ## https://wiki.archlinux.org/title/PipeWire#Changing_the_default_sample_rate
    default.clock.rate = 48000

    ## https://wiki.archlinux.org/title/PipeWire#Sound_quality_(resampling_quality)
    resample.quality = 14

    default.clock.min-quantum = 16
    default.clock.max-quantum = 512
}
