## https://this.ven.uber.space/docs/computer/pro-audio/#sound-server

context.properties = {
    ## https://wiki.archlinux.org/title/PipeWire#Sound_quality
    default.clock.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]

    default.clock.min-quantum = 16
    default.clock.max-quantum = 128
}
