[conda]
# Additional named conda environments to update (`conda env update -n env_name`)
# env_names = [
#     "Toolbox",
#     "PyTorch"
# ]
# Additional conda environment paths to update (`conda env update -p env_path`)
# env_paths = [
#     "~/webserver/.conda/",
#     "~/experiments/.conda/"
# ]
