# containers = ["archlinux-latest"]
[containers]
# Specify the containers to ignore while updating (Wildcard supported)
# ignored_containers = ["ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest", "docker.io*"]
# Specify the runtime to use for containers (default: "docker", allowed values: "docker", "podman")
# runtime = "podman"

# Run 'docker system prune' to clean up unused containers, networks, and build cache
# (default: false)
# system_prune = false

# Use sudo for updating containers. Necessary for non-rootless installs.
# (default: false)
# use_sudo = false
