[lensfun]
# If disabled, Topgrade invokes `lensfun‑update‑data` without root privilege,
# then the update will be only available to you. Otherwise, `sudo` is required,
# and the update will be installed system-wide, i.e., available to all users.
# (default: false)
# use_sudo = false
