# The parameters were taken from the following pages
# 1st parameter: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Kernel_module_parameters
# 2nd and 3rd parameters: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend
# 4th parameter: https://wiki.archlinux.org/title/NVIDIA/Troubleshooting#Fix_graphical_corruption_in_GNOME_Shell_when_resuming_from_sleep
# 5th parameter: https://wiki.archlinux.org/title/Improving_performance#Enabling_PCIe_resizable_BAR
# 6th parameter: https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/kernel-open/nvidia/nv-reg.h

# Read more here: https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/kernel-open/nvidia/nv-reg.h

options nvidia NVreg_RegistryDwords="OverrideMaxPerf=0x1" NVreg_UseKernelSuspendNotifiers=1 NVreg_TemporaryFilePath="/var/tmp" NVreg_DynamicPowerManagement=0x02 NVreg_EnableResizableBar=1 NVreg_EnableGpuFirmwareLogs=1

###################################################################

# The parameters were taken from the following pages
# 1st parameter: https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting
# 2nd parameter: https://wiki.archlinux.org/title/NVIDIA#fbdev

## These are no longer necessary, only still here for older driver versions that require manual intervention for enabling these features.
#options nvidia_drm modeset=1 fbdev=1
