# The parameters were taken from the following pages
# 1st parameter: https://wiki.archlinux.org/title/NVIDIA#Enabling_brightness_control
# 2nd and 3rd parameters: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Kernel_module_parameters
# 4th and 5th parameters: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend
# 6th parameter: https://wiki.archlinux.org/title/NVIDIA/Troubleshooting#Fix_graphical_corruption_in_GNOME_Shell_when_resuming_from_sleep


options nvidia NVreg_RegistryDwords="EnableBrightnessControl=1" NVreg_UsePageAttributeTable=1 NVreg_RegistryDwords="OverrideMaxPerf=0x1" NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath="/var/tmp" NVreg_DynamicPowerManagement=0x02

###################################################################

# The parameters were taken from the following pages
# 1st parameter: https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting
# 2nd parameter: https://wiki.archlinux.org/title/NVIDIA#fbdev


options nvidia_drm modeset=1 fbdev=1
