## https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Loading_vfio-pci_early

softdep nvidia pre: vfio-pci

## https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Binding_vfio-pci_via_device_ID
# Use lspci to find the PCI adresses for the Nvidia dGPU and other devices in its IOMMU group

options vfio_pci ids=10de:2860,10de:22bd
