# Extra settings can be found here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# And here: https://alacritty.org/config-alacritty.html

####################################################################

[cursor]
blink_interval = 500 # Milliseconds
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Always"

####################################################################

# Make sure the font you want to use is installed.
[font]
size = 10.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

####################################################################

[general]
import = [ "~/.config/alacritty/themes/xterm.toml" ]

####################################################################

[scrolling]
history = 2666

####################################################################

[terminal.shell]
program = "/bin/bash"

####################################################################

[window]
opacity = 0.77

#padding.x = 10
#padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

dynamic_title = true

[window.dimensions]
#lines = 42
#columns = 117
