# Don't include consecutive duplicate commands or commands starting with a space in ~/.bash_history
## https://unix.stackexchange.com/questions/48713/how-can-i-remove-duplicates-in-my-bash-history-preserving-order
HISTCONTROL=ignorespace:ignoredups:erasedups

# Control the history size
HISTSIZE=666
HISTFILESIZE=3690

# Add timestamp to the history command (not the file)
HISTTIMEFORMAT="%A, %d/%m/%Y %T: "
