## https://wiki.archlinux.org/title/Systemd-boot#Loader_configuration
## https://man.archlinux.org/man/loader.conf.5#OPTIONS

auto-entries      yes
auto-firmware     yes
auto-poweroff     yes
auto-reboot       yes
beep              no
console-mode      keep
#default           archlinux-bazzite.conf
#default           auto-windows
editor            no
log-level         info
reboot-on-error   yes
timeout           3
