## https://wiki.archlinux.org/title/Systemd-boot#Loader_configuration
## https://man.archlinux.org/man/loader.conf.5#OPTIONS

#default         archlinux-bazzite.conf
timeout         3
console-mode    keep
editor          no
auto-firmware   yes
beep            no
